In [3]:
import tensorflow as tf
import numpy as np

In [2]:
inputs1 = tf.placeholder(shape=[1,16],dtype=tf.float32)
W = tf.Variable(tf.random_uniform([16,4],0,0.01))
Qout = tf.matmul(inputs1,W)

In [3]:
grad_Qout_inputs1 = tf.gradients(Qout, inputs1)

In [6]:
init = tf.global_variables_initializer()

In [6]:
sess = tf.Session()

In [8]:
sess.run(init)

In [9]:
inp = np.random.random([1,16])
print inp

[[ 0.87524002  0.0094723   0.8894848   0.14934706  0.80394238  0.657297
   0.80094088  0.24082964  0.52653745  0.63124134  0.07451427  0.12918606
   0.08579958  0.54836739  0.25862092  0.27553645]]


In [10]:
Qout_val = sess.run([Qout], feed_dict={inputs1:inp})

In [11]:
Qout_val

[array([[ 0.03430185,  0.03604505,  0.03762769,  0.03974636]], dtype=float32)]

In [12]:
grad_Qout_inputs1_val = sess.run([grad_Qout_inputs1], feed_dict={inputs1:inp})
# optimizer = tf.train.GradientDescentOptimizer(learning_rate = 0.01)
# grad_Qout_W = optimizer.compute_gradients(Qout,[W])

In [43]:
grad_Qout_inputs1_val[0][0]

array([[ 0.0208045 ,  0.01549817,  0.02198123,  0.02068668,  0.01678517,
         0.01889607,  0.02400613,  0.0355617 ,  0.02379965,  0.02304302,
         0.0130398 ,  0.0254944 ,  0.01931266,  0.02321273,  0.01793681,
         0.00961783]], dtype=float32)

In [32]:
sess.run(W)

array([[ 0.00238261,  0.00420109,  0.00555477,  0.00866603],
       [ 0.00318701,  0.00235641,  0.00752537,  0.00242939],
       [ 0.00652695,  0.00506918,  0.00922542,  0.00115968],
       [ 0.00650745,  0.00124516,  0.005386  ,  0.00754807],
       [ 0.00657544,  0.00107916,  0.00297415,  0.00615643],
       [ 0.0064905 ,  0.0015887 ,  0.0032183 ,  0.00759857],
       [ 0.0061574 ,  0.00808443,  0.00226643,  0.00749787],
       [ 0.00998877,  0.00780671,  0.00893512,  0.0088311 ],
       [ 0.00220606,  0.00805287,  0.00534034,  0.00820039],
       [ 0.00326426,  0.00881891,  0.00613262,  0.00482722],
       [ 0.00279902,  0.00043439,  0.00836182,  0.00144457],
       [ 0.00938173,  0.00771476,  0.00331546,  0.00508245],
       [ 0.00999137,  0.00688531,  0.00200177,  0.00043421],
       [ 0.00505136,  0.00547555,  0.00727855,  0.00540726],
       [ 0.00069669,  0.00843407,  0.0071282 ,  0.00167785],
       [ 0.00025025,  0.00280608,  0.0053345 ,  0.00122699]], dtype=float32)

In [34]:
sess.run(tf.shape(W))

array([16,  4], dtype=int32)

In [38]:
sess.run(tf.reduce_sum(W,1))

array([ 0.0208045 ,  0.01549817,  0.02198123,  0.02068668,  0.01678517,
        0.01889607,  0.02400613,  0.0355617 ,  0.02379965,  0.02304302,
        0.0130398 ,  0.0254944 ,  0.01931266,  0.02321273,  0.01793681,
        0.00961783], dtype=float32)

In [47]:
sess.run(tf.shape(Qout)[1])

4

In [51]:
jacobian = tf.stack([tf.gradients(Qout[0][i], inputs1)[0][0] for i in range(sess.run(tf.shape(Qout)[1]))])

In [59]:
j1,j2 = jacobian[:,:5], jacobian[:,5:]

In [61]:
sess.run(tf.shape(j2))

array([ 4, 11], dtype=int32)

In [54]:
sess.run(jacobian, feed_dict={inputs1:inp})

array([[ 0.00238261,  0.00318701,  0.00652695,  0.00650745,  0.00657544,
         0.0064905 ,  0.0061574 ,  0.00998877,  0.00220606,  0.00326426,
         0.00279902,  0.00938173,  0.00999137,  0.00505136,  0.00069669,
         0.00025025],
       [ 0.00420109,  0.00235641,  0.00506918,  0.00124516,  0.00107916,
         0.0015887 ,  0.00808443,  0.00780671,  0.00805287,  0.00881891,
         0.00043439,  0.00771476,  0.00688531,  0.00547555,  0.00843407,
         0.00280608],
       [ 0.00555477,  0.00752537,  0.00922542,  0.005386  ,  0.00297415,
         0.0032183 ,  0.00226643,  0.00893512,  0.00534034,  0.00613262,
         0.00836182,  0.00331546,  0.00200177,  0.00727855,  0.0071282 ,
         0.0053345 ],
       [ 0.00866603,  0.00242939,  0.00115968,  0.00754807,  0.00615643,
         0.00759857,  0.00749787,  0.0088311 ,  0.00820039,  0.00482722,
         0.00144457,  0.00508245,  0.00043421,  0.00540726,  0.00167785,
         0.00122699]], dtype=float32)

In [57]:
sess.run(tf.transpose(jacobian), feed_dict={inputs1:inp})

array([[ 0.00238261,  0.00420109,  0.00555477,  0.00866603],
       [ 0.00318701,  0.00235641,  0.00752537,  0.00242939],
       [ 0.00652695,  0.00506918,  0.00922542,  0.00115968],
       [ 0.00650745,  0.00124516,  0.005386  ,  0.00754807],
       [ 0.00657544,  0.00107916,  0.00297415,  0.00615643],
       [ 0.0064905 ,  0.0015887 ,  0.0032183 ,  0.00759857],
       [ 0.0061574 ,  0.00808443,  0.00226643,  0.00749787],
       [ 0.00998877,  0.00780671,  0.00893512,  0.0088311 ],
       [ 0.00220606,  0.00805287,  0.00534034,  0.00820039],
       [ 0.00326426,  0.00881891,  0.00613262,  0.00482722],
       [ 0.00279902,  0.00043439,  0.00836182,  0.00144457],
       [ 0.00938173,  0.00771476,  0.00331546,  0.00508245],
       [ 0.00999137,  0.00688531,  0.00200177,  0.00043421],
       [ 0.00505136,  0.00547555,  0.00727855,  0.00540726],
       [ 0.00069669,  0.00843407,  0.0071282 ,  0.00167785],
       [ 0.00025025,  0.00280608,  0.0053345 ,  0.00122699]], dtype=float32)

In [ ]:
# define symbolic variables
x = tf.placeholder("float") 
y = tf.placeholder("float")

# define a function R=R(x,y)
R = 0.127-(x*0.194/(y+0.194))

# The derivative of R with respect to y
Rdy = tf.gradients(R, y); 

# Launch a session for the default graph to comput dR/dy at (x,y)=(0.362, 0.556)
sess = tf.Session()
result = sess.run(Rdy, {x:0.362,y:0.556})
print result
#[0.12484978]

In [67]:
#Jacobian test
x = tf.placeholder(shape=[None, 2], dtype=tf.float32)
y1 = tf.square(x)[:,0] + tf.square(x)[:,1]
y2 = tf.pow(x[:,0], 3)+ tf.pow(x[:,1], 3)
y3 = tf.pow(x[:,0], 4)+ tf.pow(x[:,1], 4)
y = tf.stack([y1,y2,y3],axis=1)

In [89]:
inp = np.asarray([[1,2], [3,4], [5,6], [7,8]])
mini_inp = np.asarray([[1,2],[3,4]])

In [74]:
sess.run([y], {x:inp})

[array([[  5.00000000e+00,   9.00000000e+00,   1.70000000e+01],
        [  2.50000000e+01,   9.10000000e+01,   3.37000000e+02],
        [  6.10000000e+01,   3.41000000e+02,   1.92100000e+03],
        [  1.13000000e+02,   8.55000000e+02,   6.49700000e+03]], dtype=float32)]

In [72]:
grad1 = tf.gradients(y1,x)
grad2 = tf.gradients(y2,x)
grad3 = tf.gradients(y3,x)
grad = tf.gradients(y,x)

In [95]:
def compute_jacobian(f, x, f_dim): 
    jacobian = tf.stack([tf.gradients(f[:,i], x) for i in range(f_dim)])
    return jacobian

In [83]:
sess.run([grad1, grad2, grad3, grad],{x:inp})

[[array([[  2.,   4.],
         [  6.,   8.],
         [ 10.,  12.],
         [ 14.,  16.]], dtype=float32)], [array([[   3.,   12.],
         [  27.,   48.],
         [  75.,  108.],
         [ 147.,  192.]], dtype=float32)], [array([[    4.,    32.],
         [  108.,   256.],
         [  500.,   864.],
         [ 1372.,  2048.]], dtype=float32)], [array([[    9.,    48.],
         [  141.,   312.],
         [  585.,   984.],
         [ 1533.,  2256.]], dtype=float32)]]

In [94]:
print sess.run([y,y[:,0]],{x:inp})

[array([[  5.00000000e+00,   9.00000000e+00,   1.70000000e+01],
       [  2.50000000e+01,   9.10000000e+01,   3.37000000e+02],
       [  6.10000000e+01,   3.41000000e+02,   1.92100000e+03],
       [  1.13000000e+02,   8.55000000e+02,   6.49700000e+03]], dtype=float32), array([   5.,   25.,   61.,  113.], dtype=float32)]


In [97]:
j = compute_jacobian(y,x,3)
print sess.run([grad1,grad2,grad3,j], {x:mini_inp})

[[array([[ 2.,  4.],
       [ 6.,  8.]], dtype=float32)], [array([[  3.,  12.],
       [ 27.,  48.]], dtype=float32)], [array([[   4.,   32.],
       [ 108.,  256.]], dtype=float32)], array([[[[   2.,    4.],
         [   6.,    8.]]],


       [[[   3.,   12.],
         [  27.,   48.]]],


       [[[   4.,   32.],
         [ 108.,  256.]]]], dtype=float32)]
